name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      
      with:
        java-version: '11'
        distribution: 'zulu'
        maven-version: 'default'

    - name: Build with Maven
      run: mvn clean package

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: raghava017
        password: Raghava@9010 

    - name: Build Docker image
      run: docker build -t raghava017/test:latest .
      
    - name: Push Docker image to Docker Hub
      run: docker push raghava017/test:latest
      
    - name: Install SSH
      run: sudo apt-get install openssh-client
      
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2 instance
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ec2-user@52.91.190.83 << 'EOF'
          docker pull raghava017/test:latest
          docker run -d --name test -p 80:80 raghava017/test:latest
        EOF
